log:
  level: debug
  console:
    encoding: json

session:
  cookie_name: webauthn
  secure: yes
  domain: example.com

listen_address: "0.0.0.0:8080"
ssl_enabled: "no"
ssl_cert_file: domain.crt
ssl_key_file: domain.key
external_url: EXTERNAL_URL

display_name: Webauthn
conveyance_preference: indirect
authenticator_attachment: cross-platform
user_verification_requirement: preferred