# This workflow creates docker image and deploys it to GCP as cloud run

name: GCP Webauthn server

# trigger workflow
on:
  workflow_dispatch:
    inputs:
      Env:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  package-docker-image:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.Env }}
    permissions:
      # Add "id-token" with the intended permissions.
      id-token: write
      contents: read
    #outputs:
    # webauthn_image_id: ${{ steps.
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
      - name: Run makefile
        id: make-package
        run: |
          sed  's/EXTERNAL_URL/${{ vars.EXTERNAL_URL }}/' config.example.yaml > config.yaml
          echo "Generating the script..."
          make --just-print package > tempscript.sh
          chmod +x tempscript.sh
          echo "Running the script..."
          ./tempscript.sh
          
      # Configure workload identity federation
      #- name: Authenticate to Google Cloud
      #  id: gcp_auth
      #  uses: 'google-github-actions/auth@v0'
      #  with:
      #    workload_identity_provider: ${{ secrets.GCP_Workload_IDP_Name }}
      #    service_account: ${{ secrets.GCP_SERVICE_ACCT }}

      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          install_components: 'beta'

      # Check the active identity of login user
      - name: Check identity
        id: validate
        run: |
          gcloud auth list
