# This workflow creates docker image and deploys it to GCP as cloud run

name: GCP Webauthn server

# trigger workflow
on:
  workflow_dispatch:
    inputs:
      Env:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  package-docker-image:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.Env }}
    permissions:
      # Add "id-token" with the intended permissions.
      id-token: write
      contents: read
    #outputs:
    # webauthn_image_id: ${{ steps.
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v3
      - name: Run makefile
        id: make-package
        run: |
          sed  's/EXTERNAL_URL/${{ vars.EXTERNAL_URL }}/' config.example.yaml > config.yaml
          echo "Generating the script..."
          make --just-print package > tempscript.sh
          chmod +x tempscript.sh
          echo "Running the script..."
          ./tempscript.sh

      # Configure workload identity federation
      - name: Authenticate to Google Cloud
        id: gcp_auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_Workload_IDP_Name }}
          service_account: ${{ secrets.GCP_SERVICE_ACCT }}

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.gcp_auth.outputs.access_token }}'
          registry: '${{ secrets.GCP_ARTIFACTORY_LOCATION }}-docker.pkg.dev'

      - name: Tag and Push Container
        id: push-container
        run: |-
          docker tag "${{ secrets.GCP_CLOUD_RUN_IMG_NAME }}:latest" "${{ secrets.GCP_ARTIFACTORY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_CLOUD_RUN_IMG_NAME }}:latest"
          docker push "${{ secrets.GCP_ARTIFACTORY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_CLOUD_RUN_IMG_NAME }}:latest"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ secrets.GCP_CLOUD_RUN_SERVICE_NAME }}
          region: ${{ secrets.GCP_CLOUD_RUN_SERVICE_REGION }}
          # NOTE: If using a pre-built image, update the image name here
          image: ${{ secrets.GCP_ARTIFACTORY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_CLOUD_RUN_IMG_NAME }}:latest

